package taskCollections;

import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;

public class Task4Tests {
    static Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        //User give start number of random range.
        //The program will generate a scope of 49 random numbers
        //The scope begins from start number given by User
        System.out.println("Random range from 49 numbers will generated");
        System.out.print("Give the start number of this range: ");
        int startR = 0;
        int endR;
        if (sc.hasNextInt()) {
            startR = sc.nextInt();
        }
        endR = startR + 49;


        //The program generate a scope of 49 random numbers
        int count = 0;
        int[] randArr49 = new int[49];
        while (count != 49) {
            randArr49[count] = startR + (int) (Math.random() * ((endR - startR) + 1));
            count++;
        }
        //The program shows User these numbers
        System.out.println("Choose six unique numbers from displayed");
        for (Integer x : randArr49) {
            System.out.print(x + " ");
        }
        System.out.println("");

        //User choose six numbers from the scope
        //If User will chose number out of scope
        //or it will be repeated number
        //The program makes User repeat the choice
        int userCount6 = 0;
        int userInput;
        Set<Integer> userRange = new HashSet<>(6);
        while (userRange.size() != 6) {
            boolean flag = false;
            System.out.print("your choice: ");
            if (sc.hasNextInt()) {
                userInput = sc.nextInt();
                for (Integer x : randArr49) {
                    if (userInput == x) {
                        userRange.add(x);
                        userCount6++;
                        flag = true;
                    }
                }
                if (flag == false) System.out.println("You've chosen number out of range");
            }
        }
        //Show numbers are chosen by User
        System.out.print("The numbers are chosen by you: ");
        for (Integer x : userRange) System.out.print(x + " ");
        System.out.println("");

        //The program begin generate six random numbers from the scope
        //Till the all generated numbers will equal User's numbers
        int compRand;
        int compCount = 0;
        Set<Integer> computerCollection = new HashSet<>(6);
        while (!computerCollection.equals(userRange)) {

            compRand = startR + (int) (Math.random() * ((endR - startR) + 1));
            for (Integer x : userRange) {
                if (compRand == x) computerCollection.add(compRand);
            }
            compCount++;
        }

        //Show generated numbers
        System.out.print("The numbers are generated by the program: ");
        for (Integer x : computerCollection) System.out.print(x + " ");
        System.out.println("");
        System.out.println("##Numbers of cycles: " + compCount);

        int year, day = 0;
        year = compCount / 365;

        if (compCount % 365 == 0) {
            System.out.println("The program will generate this numbers by" +
                    " Years: " + year + " Days: " + day);
        } else if (year < 1) {
            day = compCount;
            System.out.println("The program will generate this numbers by" +
                    " Years: " + year + " Days: " + day);
        } else {
            day = compCount - 365 * year;
            System.out.println("The program will generate this numbers by" +
                    " Years: " + year + " Days: " + day);
        }
    }
}
